### ISSUE TITLE
Activate gives error 500

### ISSUE THREAD

**Issue by crancino** [esuarezsantana/yourls-edition-logger#4]
Hi,
I followed all the steps in order to get the plugin working but when I click on Activate it gives error 500.
Permissions on files and folders looks ok, klogger is in the right place, the constants are added at the end of user/config.php as told.
No error is reported in logs.
Any idea?
Thanks,
Alex

**Comment by esuarezsantana** [comment]
Sorry, not working anymore on this project.

**Comment by m7ess5** [comment]
hi crancino, i have the same issue, have you found out how to solve it ??

**Comment by gmolop** [comment]
Same problem and solution as #3 
Download Klogger v0.2.0 from [older released list](https://github.com/katzgrau/KLogger/releases)  and it should work.
<sup>(very old btw, upgrade is recommended)</sup>

**Comment by esuarezsantana** [comment]
I guess I can close this.
